<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\Dodo.Unique.NewtonsoftJson\Dodo.Unique.NewtonsoftJson.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="TUnit" />
        <PackageReference Include="Newtonsoft.Json" />
    </ItemGroup>
</Project>
